name: build

on:
  pull_request:
  push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    name: Run golangci-lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  gofmt:
    runs-on: ubuntu-latest
    name: Run gofmt
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
      - name: gofmt
        run: make check     
  build:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
      - name: build
        run: make build     
